# -*- coding: utf-8 -*-
"""Web_Appi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z532Ho8nxChsyE2-Edk1jMTWHXQGQEa9
"""

! pip install streamlit

import numpy as np # constructing arrays 
import skimage.io as io # read images in from files on your computer, to a form usable in a Python program
import matplotlib.pyplot as plt # what does?
from PIL import Image # data visualization, typically in the form of plots, graphs and charts
import glob # list of pics
from PIL.ExifTags import TAGS 
import cv2 as cv2 
import streamlit as st

logo = 'logo.png'

# main page
st.set_page_config(page_title='Bring It', page_icon = logo , layout = 'wide', initial_sidebar_state = 'auto')
st.title('Image Something Using Somewhat by Reem Har Levi')

